# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ijaehyeon/source/42_printf

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ijaehyeon/source/42_printf

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ijaehyeon/source/42_printf/CMakeFiles /Users/ijaehyeon/source/42_printf//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ijaehyeon/source/42_printf/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ft_printf

# Build rule for target.
ft_printf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ft_printf
.PHONY : ft_printf

# fast build rule for target.
ft_printf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/build
.PHONY : ft_printf/fast

#=============================================================================
# Target rules for targets named libft

# Build rule for target.
libft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libft
.PHONY : libft

# fast build rule for target.
libft/fast:
	$(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/build
.PHONY : libft/fast

src/free_fmt_arg.o: src/free_fmt_arg.c.o
.PHONY : src/free_fmt_arg.o

# target to build an object file
src/free_fmt_arg.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/free_fmt_arg.c.o
.PHONY : src/free_fmt_arg.c.o

src/free_fmt_arg.i: src/free_fmt_arg.c.i
.PHONY : src/free_fmt_arg.i

# target to preprocess a source file
src/free_fmt_arg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/free_fmt_arg.c.i
.PHONY : src/free_fmt_arg.c.i

src/free_fmt_arg.s: src/free_fmt_arg.c.s
.PHONY : src/free_fmt_arg.s

# target to generate assembly for a file
src/free_fmt_arg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/free_fmt_arg.c.s
.PHONY : src/free_fmt_arg.c.s

src/ft_printf.o: src/ft_printf.c.o
.PHONY : src/ft_printf.o

# target to build an object file
src/ft_printf.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/ft_printf.c.o
.PHONY : src/ft_printf.c.o

src/ft_printf.i: src/ft_printf.c.i
.PHONY : src/ft_printf.i

# target to preprocess a source file
src/ft_printf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/ft_printf.c.i
.PHONY : src/ft_printf.c.i

src/ft_printf.s: src/ft_printf.c.s
.PHONY : src/ft_printf.s

# target to generate assembly for a file
src/ft_printf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/ft_printf.c.s
.PHONY : src/ft_printf.c.s

src/gc_utox.o: src/gc_utox.c.o
.PHONY : src/gc_utox.o

# target to build an object file
src/gc_utox.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/gc_utox.c.o
.PHONY : src/gc_utox.c.o

src/gc_utox.i: src/gc_utox.c.i
.PHONY : src/gc_utox.i

# target to preprocess a source file
src/gc_utox.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/gc_utox.c.i
.PHONY : src/gc_utox.c.i

src/gc_utox.s: src/gc_utox.c.s
.PHONY : src/gc_utox.s

# target to generate assembly for a file
src/gc_utox.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/gc_utox.c.s
.PHONY : src/gc_utox.c.s

src/iprintf3.o: src/iprintf3.c.o
.PHONY : src/iprintf3.o

# target to build an object file
src/iprintf3.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/iprintf3.c.o
.PHONY : src/iprintf3.c.o

src/iprintf3.i: src/iprintf3.c.i
.PHONY : src/iprintf3.i

# target to preprocess a source file
src/iprintf3.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/iprintf3.c.i
.PHONY : src/iprintf3.c.i

src/iprintf3.s: src/iprintf3.c.s
.PHONY : src/iprintf3.s

# target to generate assembly for a file
src/iprintf3.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/iprintf3.c.s
.PHONY : src/iprintf3.c.s

src/iprints_.o: src/iprints_.c.o
.PHONY : src/iprints_.o

# target to build an object file
src/iprints_.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/iprints_.c.o
.PHONY : src/iprints_.c.o

src/iprints_.i: src/iprints_.c.i
.PHONY : src/iprints_.i

# target to preprocess a source file
src/iprints_.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/iprints_.c.i
.PHONY : src/iprints_.c.i

src/iprints_.s: src/iprints_.c.s
.PHONY : src/iprints_.s

# target to generate assembly for a file
src/iprints_.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/iprints_.c.s
.PHONY : src/iprints_.c.s

src/is_conv_spec.o: src/is_conv_spec.c.o
.PHONY : src/is_conv_spec.o

# target to build an object file
src/is_conv_spec.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/is_conv_spec.c.o
.PHONY : src/is_conv_spec.c.o

src/is_conv_spec.i: src/is_conv_spec.c.i
.PHONY : src/is_conv_spec.i

# target to preprocess a source file
src/is_conv_spec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/is_conv_spec.c.i
.PHONY : src/is_conv_spec.c.i

src/is_conv_spec.s: src/is_conv_spec.c.s
.PHONY : src/is_conv_spec.s

# target to generate assembly for a file
src/is_conv_spec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/is_conv_spec.c.s
.PHONY : src/is_conv_spec.c.s

src/pprintf.o: src/pprintf.c.o
.PHONY : src/pprintf.o

# target to build an object file
src/pprintf.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/pprintf.c.o
.PHONY : src/pprintf.c.o

src/pprintf.i: src/pprintf.c.i
.PHONY : src/pprintf.i

# target to preprocess a source file
src/pprintf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/pprintf.c.i
.PHONY : src/pprintf.c.i

src/pprintf.s: src/pprintf.c.s
.PHONY : src/pprintf.s

# target to generate assembly for a file
src/pprintf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/pprintf.c.s
.PHONY : src/pprintf.c.s

src/uprint_pad.o: src/uprint_pad.c.o
.PHONY : src/uprint_pad.o

# target to build an object file
src/uprint_pad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/uprint_pad.c.o
.PHONY : src/uprint_pad.c.o

src/uprint_pad.i: src/uprint_pad.c.i
.PHONY : src/uprint_pad.i

# target to preprocess a source file
src/uprint_pad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/uprint_pad.c.i
.PHONY : src/uprint_pad.c.i

src/uprint_pad.s: src/uprint_pad.c.s
.PHONY : src/uprint_pad.s

# target to generate assembly for a file
src/uprint_pad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/uprint_pad.c.s
.PHONY : src/uprint_pad.c.s

src/vprint_fmt.o: src/vprint_fmt.c.o
.PHONY : src/vprint_fmt.o

# target to build an object file
src/vprint_fmt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/vprint_fmt.c.o
.PHONY : src/vprint_fmt.c.o

src/vprint_fmt.i: src/vprint_fmt.c.i
.PHONY : src/vprint_fmt.i

# target to preprocess a source file
src/vprint_fmt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/vprint_fmt.c.i
.PHONY : src/vprint_fmt.c.i

src/vprint_fmt.s: src/vprint_fmt.c.s
.PHONY : src/vprint_fmt.s

# target to generate assembly for a file
src/vprint_fmt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/vprint_fmt.c.s
.PHONY : src/vprint_fmt.c.s

src/vprint_hex.o: src/vprint_hex.c.o
.PHONY : src/vprint_hex.o

# target to build an object file
src/vprint_hex.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/vprint_hex.c.o
.PHONY : src/vprint_hex.c.o

src/vprint_hex.i: src/vprint_hex.c.i
.PHONY : src/vprint_hex.i

# target to preprocess a source file
src/vprint_hex.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/vprint_hex.c.i
.PHONY : src/vprint_hex.c.i

src/vprint_hex.s: src/vprint_hex.c.s
.PHONY : src/vprint_hex.s

# target to generate assembly for a file
src/vprint_hex.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/vprint_hex.c.s
.PHONY : src/vprint_hex.c.s

src/xprintf2.o: src/xprintf2.c.o
.PHONY : src/xprintf2.o

# target to build an object file
src/xprintf2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/xprintf2.c.o
.PHONY : src/xprintf2.c.o

src/xprintf2.i: src/xprintf2.c.i
.PHONY : src/xprintf2.i

# target to preprocess a source file
src/xprintf2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/xprintf2.c.i
.PHONY : src/xprintf2.c.i

src/xprintf2.s: src/xprintf2.c.s
.PHONY : src/xprintf2.s

# target to generate assembly for a file
src/xprintf2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_printf.dir/build.make CMakeFiles/ft_printf.dir/src/xprintf2.c.s
.PHONY : src/xprintf2.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ft_printf"
	@echo "... libft"
	@echo "... src/free_fmt_arg.o"
	@echo "... src/free_fmt_arg.i"
	@echo "... src/free_fmt_arg.s"
	@echo "... src/ft_printf.o"
	@echo "... src/ft_printf.i"
	@echo "... src/ft_printf.s"
	@echo "... src/gc_utox.o"
	@echo "... src/gc_utox.i"
	@echo "... src/gc_utox.s"
	@echo "... src/iprintf3.o"
	@echo "... src/iprintf3.i"
	@echo "... src/iprintf3.s"
	@echo "... src/iprints_.o"
	@echo "... src/iprints_.i"
	@echo "... src/iprints_.s"
	@echo "... src/is_conv_spec.o"
	@echo "... src/is_conv_spec.i"
	@echo "... src/is_conv_spec.s"
	@echo "... src/pprintf.o"
	@echo "... src/pprintf.i"
	@echo "... src/pprintf.s"
	@echo "... src/uprint_pad.o"
	@echo "... src/uprint_pad.i"
	@echo "... src/uprint_pad.s"
	@echo "... src/vprint_fmt.o"
	@echo "... src/vprint_fmt.i"
	@echo "... src/vprint_fmt.s"
	@echo "... src/vprint_hex.o"
	@echo "... src/vprint_hex.i"
	@echo "... src/vprint_hex.s"
	@echo "... src/xprintf2.o"
	@echo "... src/xprintf2.i"
	@echo "... src/xprintf2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

